import turtle

t = turtle.Turtle()
s = turtle.Screen()
A = 100
turtle.color("green")
#turtle.fillcolor("green")
turtle.begin_fill()
#main body
turtle.right
turtle.backward(300)
turtle.forward(600)
turtle.left(90)
turtle.forward(A)
turtle.left(90)
turtle.forward(600)
turtle.left(90)
turtle.forward(A)
turtle.end_fill()
#head
turtle.begin_fill()
turtle.backward(A)
turtle.right(138)
turtle.forward(A)
turtle.left(A)
turtle.forward(A)
turtle.left(128)
turtle.forward(740)
#tail
turtle.left(79)
turtle.forward(90)
turtle.left(45)
turtle.forward(A)
turtle.left(90)
turtle.forward(10)
turtle.left(90)
turtle.forward(90)
turtle.right(45)
turtle.forward(93)
turtle.end_fill()
turtle.right(130)
turtle.color("black")
turtle.left(28.5)
turtle.forward(10)
#spikes on back
turtle.begin_fill()
for x in range(10):
    turtle.forward(30)
    turtle.left(45)
    turtle.forward(30)
    turtle.right(45)
turtle.end_fill()
#eye
turtle.up()
turtle.forward(30)
turtle.left(45)
turtle.forward(30)
turtle.right(45)
turtle.right(20)
turtle.forward(50)
turtle.down()
turtle.color("black")
turtle.color("red")
turtle.begin_fill()
turtle.circle(20)
turtle.end_fill()
turtle.right(250)
turtle.forward(10)
turtle.right(90)
turtle.forward(15)
turtle.color("blue")
turtle.begin_fill()
turtle.circle(10)
turtle.end_fill()
turtle.color("black")
#going to legs
turtle.up()
turtle.left(120)
turtle.forward(140)
turtle.left(90)
turtle.forward(75)
turtle.right(7.5)
turtle.down()
turtle.color("green")
turtle.begin_fill()
#legs one
turtle.forward(A)
turtle.right(90)
turtle.forward(A)
turtle.left(90)
turtle.forward(30)
turtle.left(90)
turtle.forward(A)
#leg two
turtle.right(90)
turtle.forward(50)
turtle.right(90)
turtle.forward(A)
turtle.left(90)
turtle.forward(30)
turtle.left(90)
turtle.forward(A)
turtle.right(90)
turtle.forward(A)
#leg three
turtle.forward(A)
turtle.right(90)
turtle.forward(A)
turtle.left(90)
turtle.forward(30)
turtle.left(90)
turtle.forward(A)
#leg four
turtle.right(90)
turtle.forward(50)
turtle.right(90)
turtle.forward(A)
turtle.left(90)
turtle.forward(30)
turtle.left(90)
turtle.forward(A)
turtle.right(90)
turtle.end_fill()
s.exitonclick()